/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elfak.master;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.apache.spark.sql.types.DataTypes;
import org.apache.spark.sql.types.StructField;
import org.apache.spark.sql.types.StructType;

/**
 *
 * @author igord
 */
public class DataUtils {

    public static List<String> allSensors = Arrays.asList("raw_acc", "proc_gyro",
            "raw_magnet", "watch_acceleration", "watch_heading", "location",
            "audio_naive", "audio_properties", "discrete", "lf_measurements");
    // TODO:
    public static List<String> basicSensors = Arrays.asList("raw_acc", "proc_gyro",
            "watch_acceleration", "location", "audio_naive", "discrete");
    public static List<String> selectedSensors = Arrays.asList(/*"raw_acc", "proc_gyro",
            "watch_acceleration", "location",*/ "audio_naive", "discrete");
//    public static List<String> primaryActivities = Arrays.asList(
//            "FIX_walking", "FIX_running", "BICYCLING", "SITTING", "LYING_DOWN");
    public static List<String> primaryActivities = Arrays.asList(
            "PHONE_IN_HAND", "PHONE_IN_BAG", "PHONE_ON_TABLE",
            "PHONE_IN_POCKET");
//        public static List<String> primaryActivities = Arrays.asList(
//            "TOILET", "BATHING_-_SHOWER", "IN_CLASS",
//            "IN_A_MEETING", "FIX_restaurant");
    public static List<String> allFeatures = Arrays.asList(
            "raw_acc:magnitude_stats:mean",
            "raw_acc:magnitude_stats:std",
            "raw_acc:magnitude_stats:moment3",
            "raw_acc:magnitude_stats:moment4",
            "raw_acc:magnitude_stats:percentile25",
            "raw_acc:magnitude_stats:percentile50",
            "raw_acc:magnitude_stats:percentile75",
            "raw_acc:magnitude_stats:value_entropy",
            "raw_acc:magnitude_stats:time_entropy",
            "raw_acc:magnitude_spectrum:log_energy_band0",
            "raw_acc:magnitude_spectrum:log_energy_band1",
            "raw_acc:magnitude_spectrum:log_energy_band2",
            "raw_acc:magnitude_spectrum:log_energy_band3",
            "raw_acc:magnitude_spectrum:log_energy_band4",
            "raw_acc:magnitude_spectrum:spectral_entropy",
            "raw_acc:magnitude_autocorrelation:period",
            "raw_acc:magnitude_autocorrelation:normalized_ac",
            "raw_acc:3d:mean_x",
            "raw_acc:3d:mean_y",
            "raw_acc:3d:mean_z",
            "raw_acc:3d:std_x",
            "raw_acc:3d:std_y",
            "raw_acc:3d:std_z",
            "raw_acc:3d:ro_xy",
            "raw_acc:3d:ro_xz",
            "raw_acc:3d:ro_yz",
            "proc_gyro:magnitude_stats:mean",
            "proc_gyro:magnitude_stats:std",
            "proc_gyro:magnitude_stats:moment3",
            "proc_gyro:magnitude_stats:moment4",
            "proc_gyro:magnitude_stats:percentile25",
            "proc_gyro:magnitude_stats:percentile50",
            "proc_gyro:magnitude_stats:percentile75",
            "proc_gyro:magnitude_stats:value_entropy",
            "proc_gyro:magnitude_stats:time_entropy",
            "proc_gyro:magnitude_spectrum:log_energy_band0",
            "proc_gyro:magnitude_spectrum:log_energy_band1",
            "proc_gyro:magnitude_spectrum:log_energy_band2",
            "proc_gyro:magnitude_spectrum:log_energy_band3",
            "proc_gyro:magnitude_spectrum:log_energy_band4",
            "proc_gyro:magnitude_spectrum:spectral_entropy",
            "proc_gyro:magnitude_autocorrelation:period",
            "proc_gyro:magnitude_autocorrelation:normalized_ac",
            "proc_gyro:3d:mean_x",
            "proc_gyro:3d:mean_y",
            "proc_gyro:3d:mean_z",
            "proc_gyro:3d:std_x",
            "proc_gyro:3d:std_y",
            "proc_gyro:3d:std_z",
            "proc_gyro:3d:ro_xy",
            "proc_gyro:3d:ro_xz",
            "proc_gyro:3d:ro_yz",
            "raw_magnet:magnitude_stats:mean",
            "raw_magnet:magnitude_stats:std",
            "raw_magnet:magnitude_stats:moment3",
            "raw_magnet:magnitude_stats:moment4",
            "raw_magnet:magnitude_stats:percentile25",
            "raw_magnet:magnitude_stats:percentile50",
            "raw_magnet:magnitude_stats:percentile75",
            "raw_magnet:magnitude_stats:value_entropy",
            "raw_magnet:magnitude_stats:time_entropy",
            "raw_magnet:magnitude_spectrum:log_energy_band0",
            "raw_magnet:magnitude_spectrum:log_energy_band1",
            "raw_magnet:magnitude_spectrum:log_energy_band2",
            "raw_magnet:magnitude_spectrum:log_energy_band3",
            "raw_magnet:magnitude_spectrum:log_energy_band4",
            "raw_magnet:magnitude_spectrum:spectral_entropy",
            "raw_magnet:magnitude_autocorrelation:period",
            "raw_magnet:magnitude_autocorrelation:normalized_ac",
            "raw_magnet:3d:mean_x",
            "raw_magnet:3d:mean_y",
            "raw_magnet:3d:mean_z",
            "raw_magnet:3d:std_x",
            "raw_magnet:3d:std_y",
            "raw_magnet:3d:std_z",
            "raw_magnet:3d:ro_xy",
            "raw_magnet:3d:ro_xz",
            "raw_magnet:3d:ro_yz",
            "raw_magnet:avr_cosine_similarity_lag_range0",
            "raw_magnet:avr_cosine_similarity_lag_range1",
            "raw_magnet:avr_cosine_similarity_lag_range2",
            "raw_magnet:avr_cosine_similarity_lag_range3",
            "raw_magnet:avr_cosine_similarity_lag_range4",
            "watch_acceleration:magnitude_stats:mean",
            "watch_acceleration:magnitude_stats:std",
            "watch_acceleration:magnitude_stats:moment3",
            "watch_acceleration:magnitude_stats:moment4",
            "watch_acceleration:magnitude_stats:percentile25",
            "watch_acceleration:magnitude_stats:percentile50",
            "watch_acceleration:magnitude_stats:percentile75",
            "watch_acceleration:magnitude_stats:value_entropy",
            "watch_acceleration:magnitude_stats:time_entropy",
            "watch_acceleration:magnitude_spectrum:log_energy_band0",
            "watch_acceleration:magnitude_spectrum:log_energy_band1",
            "watch_acceleration:magnitude_spectrum:log_energy_band2",
            "watch_acceleration:magnitude_spectrum:log_energy_band3",
            "watch_acceleration:magnitude_spectrum:log_energy_band4",
            "watch_acceleration:magnitude_spectrum:spectral_entropy",
            "watch_acceleration:magnitude_autocorrelation:period",
            "watch_acceleration:magnitude_autocorrelation:normalized_ac",
            "watch_acceleration:3d:mean_x",
            "watch_acceleration:3d:mean_y",
            "watch_acceleration:3d:mean_z",
            "watch_acceleration:3d:std_x",
            "watch_acceleration:3d:std_y",
            "watch_acceleration:3d:std_z",
            "watch_acceleration:3d:ro_xy",
            "watch_acceleration:3d:ro_xz",
            "watch_acceleration:3d:ro_yz",
            "watch_acceleration:spectrum:x_log_energy_band0",
            "watch_acceleration:spectrum:x_log_energy_band1",
            "watch_acceleration:spectrum:x_log_energy_band2",
            "watch_acceleration:spectrum:x_log_energy_band3",
            "watch_acceleration:spectrum:x_log_energy_band4",
            "watch_acceleration:spectrum:y_log_energy_band0",
            "watch_acceleration:spectrum:y_log_energy_band1",
            "watch_acceleration:spectrum:y_log_energy_band2",
            "watch_acceleration:spectrum:y_log_energy_band3",
            "watch_acceleration:spectrum:y_log_energy_band4",
            "watch_acceleration:spectrum:z_log_energy_band0",
            "watch_acceleration:spectrum:z_log_energy_band1",
            "watch_acceleration:spectrum:z_log_energy_band2",
            "watch_acceleration:spectrum:z_log_energy_band3",
            "watch_acceleration:spectrum:z_log_energy_band4",
            "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0",
            "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1",
            "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2",
            "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3",
            "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range4",
            "watch_heading:mean_cos",
            "watch_heading:std_cos",
            "watch_heading:mom3_cos",
            "watch_heading:mom4_cos",
            "watch_heading:mean_sin",
            "watch_heading:std_sin",
            "watch_heading:mom3_sin",
            "watch_heading:mom4_sin",
            "watch_heading:entropy_8bins",
            "location:num_valid_updates",
            "location:log_latitude_range",
            "location:log_longitude_range",
            "location:min_altitude",
            "location:max_altitude",
            "location:min_speed",
            "location:max_speed",
            "location:best_horizontal_accuracy",
            "location:best_vertical_accuracy",
            "location:diameter",
            "location:log_diameter",
            "location_quick_features:std_lat",
            "location_quick_features:std_long",
            "location_quick_features:lat_change",
            "location_quick_features:long_change",
            "location_quick_features:mean_abs_lat_deriv",
            "location_quick_features:mean_abs_long_deriv",
            "audio_naive:mfcc0:mean",
            "audio_naive:mfcc1:mean",
            "audio_naive:mfcc2:mean",
            "audio_naive:mfcc3:mean",
            "audio_naive:mfcc4:mean",
            "audio_naive:mfcc5:mean",
            "audio_naive:mfcc6:mean",
            "audio_naive:mfcc7:mean",
            "audio_naive:mfcc8:mean",
            "audio_naive:mfcc9:mean",
            "audio_naive:mfcc10:mean",
            "audio_naive:mfcc11:mean",
            "audio_naive:mfcc12:mean",
            "audio_naive:mfcc0:std",
            "audio_naive:mfcc1:std",
            "audio_naive:mfcc2:std",
            "audio_naive:mfcc3:std",
            "audio_naive:mfcc4:std",
            "audio_naive:mfcc5:std",
            "audio_naive:mfcc6:std",
            "audio_naive:mfcc7:std",
            "audio_naive:mfcc8:std",
            "audio_naive:mfcc9:std",
            "audio_naive:mfcc10:std",
            "audio_naive:mfcc11:std",
            "audio_naive:mfcc12:std",
            "audio_properties:max_abs_value",
            "audio_properties:normalization_multiplier",
            "discrete:app_state:is_active",
            "discrete:app_state:is_inactive",
            "discrete:app_state:is_background",
            "discrete:app_state:missing",
            "discrete:battery_plugged:is_ac",
            "discrete:battery_plugged:is_usb",
            "discrete:battery_plugged:is_wireless",
            "discrete:battery_plugged:missing",
            "discrete:battery_state:is_unknown",
            "discrete:battery_state:is_unplugged",
            "discrete:battery_state:is_not_charging",
            "discrete:battery_state:is_discharging",
            "discrete:battery_state:is_charging",
            "discrete:battery_state:is_full",
            "discrete:battery_state:missing",
            "discrete:on_the_phone:is_False",
            "discrete:on_the_phone:is_True",
            "discrete:on_the_phone:missing",
            "discrete:ringer_mode:is_normal",
            "discrete:ringer_mode:is_silent_no_vibrate",
            "discrete:ringer_mode:is_silent_with_vibrate",
            "discrete:ringer_mode:missing",
            "discrete:wifi_status:is_not_reachable",
            "discrete:wifi_status:is_reachable_via_wifi",
            "discrete:wifi_status:is_reachable_via_wwan",
            "discrete:wifi_status:missing",
            "lf_measurements:light",
            "lf_measurements:pressure",
            "lf_measurements:proximity_cm",
            "lf_measurements:proximity",
            "lf_measurements:relative_humidity",
            "lf_measurements:battery_level",
            "lf_measurements:screen_brightness",
            "lf_measurements:temperature_ambient",
            "discrete:time_of_day:between0and6",
            "discrete:time_of_day:between3and9",
            "discrete:time_of_day:between6and12",
            "discrete:time_of_day:between9and15",
            "discrete:time_of_day:between12and18",
            "discrete:time_of_day:between15and21",
            "discrete:time_of_day:between18and24",
            "discrete:time_of_day:between21and3"
    );

    public static List<String> allLabels = Arrays.asList(
            "LYING_DOWN",
            "SITTING",
            "FIX_walking",
            "FIX_running",
            "BICYCLING",
            "SLEEPING",
            "LAB_WORK",
            "IN_CLASS",
            "IN_A_MEETING",
            "LOC_main_workplace",
            "OR_indoors",
            "OR_outside",
            "IN_A_CAR",
            "ON_A_BUS",
            "DRIVE_-_I_M_THE_DRIVER",
            "DRIVE_-_I_M_A_PASSENGER",
            "LOC_home",
            "FIX_restaurant",
            "PHONE_IN_POCKET",
            "OR_exercise",
            "COOKING",
            "SHOPPING",
            "STROLLING",
            "DRINKING__ALCOHOL_",
            "BATHING_-_SHOWER",
            "CLEANING",
            "DOING_LAUNDRY",
            "WASHING_DISHES",
            "WATCHING_TV",
            "SURFING_THE_INTERNET",
            "AT_A_PARTY",
            "AT_A_BAR",
            "LOC_beach",
            "SINGING",
            "TALKING",
            "COMPUTER_WORK",
            "EATING",
            "TOILET",
            "GROOMING",
            "DRESSING",
            "AT_THE_GYM",
            "STAIRS_-_GOING_UP",
            "STAIRS_-_GOING_DOWN",
            "ELEVATOR",
            "OR_standing",
            "AT_SCHOOL",
            "PHONE_IN_HAND",
            "PHONE_IN_BAG",
            "PHONE_ON_TABLE",
            "WITH_CO-WORKERS",
            "WITH_FRIENDS"
    );

    public static String[] LabelsToDelete(List<String> allLabels, String chosenLabel) {
        List<String> labelsToDelete = new ArrayList<>(allLabels);
        labelsToDelete.remove(chosenLabel);

        return labelsToDelete.toArray(new String[0]);
    }

    public static String[] FeaturesToDelete(List<String> allFeatures, String[] chosenSensors) {
        List<String> chosenSensorsList = Arrays.asList(chosenSensors);
        List<String> featureColumnsToDelete = new ArrayList<>(allFeatures);
        featureColumnsToDelete
                .removeIf(feature -> /*feature.startsWith("lf_")
                ||*/ chosenSensorsList.stream()
                        .anyMatch(chosenSensor -> feature.startsWith(chosenSensor)));

        return featureColumnsToDelete.toArray(new String[0]);
    }

    public static String[] FeaturesToKeep(List<String> allFeatures, String[] chosenSensors) {

        List<String> featureColumns = new ArrayList<>(allFeatures);
        List<String> featureColumnsToDelete
                = Arrays.asList(FeaturesToDelete(allFeatures, chosenSensors));
        featureColumns.removeAll(featureColumnsToDelete);

        return featureColumns.toArray(new String[0]);
    }

    public static StructType GetSchema() {
        // define schema for data
        StructField[] schemaFields = {
            DataTypes.createStructField("timestamp", DataTypes.IntegerType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:moment3", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:moment4", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:percentile25", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:percentile50", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:percentile75", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:value_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_stats:time_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_spectrum:spectral_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_autocorrelation:period", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:magnitude_autocorrelation:normalized_ac", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:mean_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:mean_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:mean_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:std_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:std_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:std_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:ro_xy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:ro_xz", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_acc:3d:ro_yz", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:moment3", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:moment4", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:percentile25", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:percentile50", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:percentile75", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:value_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_stats:time_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_spectrum:spectral_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_autocorrelation:period", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:magnitude_autocorrelation:normalized_ac", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:mean_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:mean_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:mean_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:std_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:std_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:std_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:ro_xy", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:ro_xz", DataTypes.DoubleType, true),
            DataTypes.createStructField("proc_gyro:3d:ro_yz", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:moment3", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:moment4", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:percentile25", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:percentile50", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:percentile75", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:value_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_stats:time_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_spectrum:spectral_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_autocorrelation:period", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:magnitude_autocorrelation:normalized_ac", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:mean_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:mean_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:mean_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:std_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:std_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:std_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:ro_xy", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:ro_xz", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:3d:ro_yz", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:avr_cosine_similarity_lag_range0", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:avr_cosine_similarity_lag_range1", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:avr_cosine_similarity_lag_range2", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:avr_cosine_similarity_lag_range3", DataTypes.DoubleType, true),
            DataTypes.createStructField("raw_magnet:avr_cosine_similarity_lag_range4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:moment3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:moment4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:percentile25", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:percentile50", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:percentile75", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:value_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_stats:time_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_spectrum:spectral_entropy", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_autocorrelation:period", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:magnitude_autocorrelation:normalized_ac", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:mean_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:mean_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:mean_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:std_x", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:std_y", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:std_z", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:ro_xy", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:ro_xz", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:3d:ro_yz", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:x_log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:x_log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:x_log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:x_log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:x_log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:y_log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:y_log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:y_log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:y_log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:y_log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:z_log_energy_band0", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:z_log_energy_band1", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:z_log_energy_band2", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:z_log_energy_band3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:spectrum:z_log_energy_band4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_acceleration:relative_directions:avr_cosine_similarity_lag_range4", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mean_cos", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:std_cos", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mom3_cos", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mom4_cos", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mean_sin", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:std_sin", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mom3_sin", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:mom4_sin", DataTypes.DoubleType, true),
            DataTypes.createStructField("watch_heading:entropy_8bins", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:num_valid_updates", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:log_latitude_range", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:log_longitude_range", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:min_altitude", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:max_altitude", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:min_speed", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:max_speed", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:best_horizontal_accuracy", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:best_vertical_accuracy", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:diameter", DataTypes.DoubleType, true),
            DataTypes.createStructField("location:log_diameter", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:std_lat", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:std_long", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:lat_change", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:long_change", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:mean_abs_lat_deriv", DataTypes.DoubleType, true),
            DataTypes.createStructField("location_quick_features:mean_abs_long_deriv", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc0:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc1:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc2:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc3:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc4:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc5:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc6:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc7:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc8:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc9:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc10:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc11:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc12:mean", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc0:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc1:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc2:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc3:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc4:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc5:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc6:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc7:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc8:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc9:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc10:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc11:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_naive:mfcc12:std", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_properties:max_abs_value", DataTypes.DoubleType, true),
            DataTypes.createStructField("audio_properties:normalization_multiplier", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:app_state:is_active", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:app_state:is_inactive", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:app_state:is_background", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:app_state:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_plugged:is_ac", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_plugged:is_usb", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_plugged:is_wireless", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_plugged:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_unknown", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_unplugged", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_not_charging", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_discharging", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_charging", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:is_full", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:battery_state:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:on_the_phone:is_False", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:on_the_phone:is_True", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:on_the_phone:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:ringer_mode:is_normal", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:ringer_mode:is_silent_no_vibrate", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:ringer_mode:is_silent_with_vibrate", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:ringer_mode:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:wifi_status:is_not_reachable", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:wifi_status:is_reachable_via_wifi", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:wifi_status:is_reachable_via_wwan", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:wifi_status:missing", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:light", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:pressure", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:proximity_cm", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:proximity", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:relative_humidity", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:battery_level", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:screen_brightness", DataTypes.DoubleType, true),
            DataTypes.createStructField("lf_measurements:temperature_ambient", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between0and6", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between3and9", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between6and12", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between9and15", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between12and18", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between15and21", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between18and24", DataTypes.DoubleType, true),
            DataTypes.createStructField("discrete:time_of_day:between21and3", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:LYING_DOWN", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:SITTING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:FIX_walking", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:FIX_running", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:BICYCLING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:SLEEPING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:LAB_WORK", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:IN_CLASS", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:IN_A_MEETING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:LOC_main_workplace", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:OR_indoors", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:OR_outside", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:IN_A_CAR", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:ON_A_BUS", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:DRIVE_-_I_M_THE_DRIVER", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:DRIVE_-_I_M_A_PASSENGER", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:LOC_home", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:FIX_restaurant", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:PHONE_IN_POCKET", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:OR_exercise", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:COOKING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:SHOPPING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:STROLLING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:DRINKING__ALCOHOL_", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:BATHING_-_SHOWER", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:CLEANING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:DOING_LAUNDRY", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:WASHING_DISHES", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:WATCHING_TV", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:SURFING_THE_INTERNET", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:AT_A_PARTY", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:AT_A_BAR", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:LOC_beach", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:SINGING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:TALKING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:COMPUTER_WORK", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:EATING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:TOILET", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:GROOMING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:DRESSING", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:AT_THE_GYM", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:STAIRS_-_GOING_UP", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:STAIRS_-_GOING_DOWN", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:ELEVATOR", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:OR_standing", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:AT_SCHOOL", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:PHONE_IN_HAND", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:PHONE_IN_BAG", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:PHONE_ON_TABLE", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:WITH_CO-WORKERS", DataTypes.DoubleType, true),
            DataTypes.createStructField("label:WITH_FRIENDS", DataTypes.DoubleType, true),
            DataTypes.createStructField("label_source", DataTypes.DoubleType, true)
        };
        StructType schema = DataTypes.createStructType(schemaFields);
        return schema;
    }

    public static List<String> getFold0AndroidUserIds(String type, String phone) {
        if ("test".contains(type)) {
            if ("android".equals(phone)) {
                return new ArrayList<>(Arrays.asList(
                        "0BFC35E2-4817-4865-BFA7-764742302A2D",
                        "0E6184E1-90C0-48EE-B25A-F1ECB7B9714E",
                        "1155FF54-63D3-4AB2-9863-8385D0BD0A13",
                        "1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842",
                        "27E04243-B138-4F40-A164-F40B60165CF3"
                ));
            } else {
                return new ArrayList<>(Arrays.asList(
                        "00EABED2-271D-49D8-B599-1D4A09240601",
                        "098A72A5-E3E5-4F54-A152-BBDA0DF7B694",
                        "0A986513-7828-4D53-AA1F-E02D6DF9561B",
                        "11B5EC4D-4133-4289-B475-4E737182A406",
                        "136562B6-95B2-483D-88DC-065F28409FD2",
                        "1538C99F-BA1E-4EFB-A949-6C7C47701B20",
                        "24E40C4C-A349-4F9F-93AB-01D00FB994AF"
                ));
            }
        } else {
            if ("android".equals(phone)) {
                return new ArrayList<>(Arrays.asList(
                        "33A85C34-CFE4-4732-9E73-0A7AC861B27A",
                        "40E170A7-607B-4578-AF04-F021C3B0384A",
                        "481F4DD2-7689-43B9-A2AA-C8772227162B",
                        "4E98F91F-4654-42EF-B908-A3389443F2E7",
                        "59818CD2-24D7-4D32-B133-24C2FE3801E5",
                        "59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2",
                        "61359772-D8D8-480D-B623-7C636EAD0C81",
                        "665514DE-49DC-421F-8DCB-145D0B2609AD",
                        "74B86067-5D4B-43CF-82CF-341B76BEA0F4",
                        "797D145F-3858-4A7F-A7C2-A4EB721E133C",
                        "806289BC-AD52-4CC1-806C-0CDB14D65EB6",
                        "81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0",
                        "86A4F379-B305-473D-9D83-FC7D800180EF",
                        "96A358A0-FFF2-4239-B93E-C7425B901B47",
                        "99B204C0-DD5C-4BB7-83E8-A37281B8D769",
                        "A5A30F76-581E-4757-97A2-957553A2C6AA",
                        "A7599A50-24AE-46A6-8EA6-2576F1011D81",
                        "B7F9D634-263E-4A97-87F9-6FFB4DDCB36C",
                        "BEF6C611-50DA-4971-A040-87FB979F3FC1",
                        "CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F",
                        "F50235E0-DD67-4F2A-B00B-1F31ADA998B9"
                ));
            } else {
                return new ArrayList<>(Arrays.asList(
                        "2C32C23E-E30C-498A-8DD2-0EFB9150A02E",
                        "3600D531-0C55-44A7-AE95-A7A38519464E",
                        "4FC32141-E888-4BFF-8804-12559A491D8C",
                        "5119D0F8-FCA8-4184-A4EB-19421A40DE0D",
                        "5152A2DF-FAF3-4BA8-9CA9-E66B32671A53",
                        "5EF64122-B513-46AE-BCF1-E62AAC285D2C",
                        "61976C24-1C50-4355-9C49-AAE44A7D09F6",
                        "78A91A4E-4A51-4065-BDA7-94755F0BB3BB",
                        "7CE37510-56D0-4120-A1CF-0E23351428D2",
                        "7D9BB102-A612-4E2A-8E22-3159752F55D8",
                        "8023FE1A-D3B0-4E2C-A57A-9321B7FC755F",
                        "83CF687B-7CEC-434B-9FE8-00C3D5799BE6",
                        "9759096F-1119-4E19-A0AD-6F16989C7E1C",
                        "9DC38D04-E82E-4F29-AB52-B476535226F2",
                        "A5CDF89D-02A2-4EC1-89F8-F534FDABDD96",
                        "A76A5AF5-5A93-4CF2-A16E-62353BB70E8A",
                        "B09E373F-8A54-44C8-895B-0039390B859F",
                        "B9724848-C7E2-45F4-9B3F-A1F38D864495",
                        "BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC",
                        "C48CE857-A0DD-4DDB-BEA5-3A25449B2153",
                        "CA820D43-E5E2-42EF-9798-BE56F776370B",
                        "CDA3BBF7-6631-45E8-85BA-EEB416B32A3C",
                        "CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC",
                        "D7D20E2E-FC78-405D-B346-DBD3FD8FC92B",
                        "E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3",
                        "ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2",
                        "FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF"
                ));
            }
        }
    }

}
